[package]
name = "aic-sdk-py"
version = "2.0.0"
edition = "2024"

[lib]
name = "aic_sdk"
crate-type = ["cdylib"]

[dependencies]
aic-sdk = { version = "0.13.0", features = [ "download-model", "download-lib" ] }
numpy = "0.27"
pyo3 = { version = "0.27", features = ["extension-module"] }
pyo3-async-runtimes = { version = "0.27", features = ["tokio-runtime"] }
tokio = { version = "1.49", features = ["rt", "rt-multi-thread"] }

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
