[package]
edition = "2024"
name = "aic-sdk-py"
rust-version = "1.87"
version = "2.1.0"

[lib]
crate-type = ["cdylib"]
name = "aic_sdk"

[dependencies]
aic-sdk = { git = "https://github.com/ai-coustics/aic-sdk-rs", branch = "next", features = ["download-model"] }
numpy = "0.27"
pyo3 = { version = "0.27", features = ["extension-module", "generate-import-lib"] }
pyo3-async-runtimes = { version = "0.27", features = ["tokio-runtime"] }
tokio = { version = "1.49", features = ["rt", "rt-multi-thread"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
